### ISSUE TITLE
Support for Webots 2022b

### ISSUE THREAD

**Issue by wuhanstudio** [knmcguire/crazyflie_ros2_experimental#3]
Hi,

May I ask how can I port this project to Webots 2022b?

I tried this project with **ros2 humble** and **Webots 2022b**. The project compiled with no error, but the drone did not take off after running this command:

```
$ ros2 launch crazyflie_ros2_simple_mapper simple_mapper_simulation_launch.py
```

And I cannot control the robot using:

```
$ ros2 run teleop_twist_keyboard teleop_twist_keyboard
```
Thanks a lot for your help.

![image](https://user-images.githubusercontent.com/15157070/201177405-34299395-c427-4df9-922a-484666b0c1cb.png)

![image](https://user-images.githubusercontent.com/15157070/201177584-68e86024-011f-417f-b312-311fc7165a38.png)

**Comment by michtesar** [comment]
Hi @wuhanstudio any news on this one? I finally got some Ubuntu computer and tried with Humble as well.

**Comment by wuhanstudio** [comment]
Hi, @michtesar 

I did not manage to control the simulated robot using Webots R2022b. Perhaps it's better to use Webots R2022a for this project.

**Comment by michtesar** [comment]
@wuhanstudio I see went for ROS Galactic and Webots R2022a and it cannot connect to the driver and does not work either.
![Screenshot from 2023-01-29 10-01-23](https://user-images.githubusercontent.com/16868864/215316109-25c3fbcc-2ccb-4ea3-9dd4-0c6f77e1fe56.png)
Do I do something wrong?

**Comment by wuhanstudio** [comment]
Did you set up the environment variables:

```
export WEBOTS_CONTROLLER_URL=ipc://1234/Crazyflie
export WEBOTS_HOME=/home/wuhanstudio/.ros/webotsR2022b/webots
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WEBOTS_HOME/lib/controller
export PYTHONIOENCODING=UTF-8
export PYTHONPATH=$PYTHONPATH:$WEBOTS_HOME/lib/controller/python38
```

**Comment by michtesar** [comment]
With that setup I get the same as you. No errors, but controller does not work. I also tried to forge in the 2022a but no luck.

**Comment by michtesar** [comment]
@knmcguire hi 👋 do you have any idea what we do wrong here?

**Comment by knmcguire** [comment]
I haven't tried it on humble at all actually. 

There are things that needs to be updated indeed... actually webots 2022b has the crazyflie in there already, so perhaps I should rewrite it with removing the model from this repository. 

Did you update the ROS2 driver for webots too?

**Comment by michtesar** [comment]
I went for Galactic short after I realized it won’t work, so I did tried both ROS 2 versions. 

I installed all dependencies and all Webots packages available. 

When I run it from Galactic and Webots 2022a I get time out after a while, because Webots cannot connect to the controller. 

For Webots 2022b, it gets connected, but the controller does not work as @wuhanstudio reported. 

I am flexible in which version to try, but at this point I am unsure where the problem is.

**Comment by knmcguire** [comment]
Alright, I haven't looked at this project for a while so I'll need to find some time for it to figure out what is going wrong. It could be that the current version on webots_ros2 doesn't work for webots 2022a.

Do mind that I'm abandoning this project for the sake of crazyswarm2. I'm currently in the works of [integrating the webots simulator](https://github.com/IMRCLab/crazyswarm2/pull/179) in there. A previous attempt was more closer to what I've done with this project but then with webots2022a https://github.com/IMRCLab/crazyswarm2/pull/106

**Comment by michtesar** [comment]
Ok, I will have a look there and continue with testing there. Which Webots version you use?

**Comment by knmcguire** [comment]
For the old PR 2022b, but for the current one 2023a

**Comment by knmcguire** [comment]
Could you try out this PR? https://github.com/knmcguire/crazyflie_ros2_experimental/pull/6. I've updated it for 2023a.

don't forget to do another colcon build
