### ISSUE TITLE
Drone connects (I think) and teleop twist command works but simple mapper launch script wont run

### ISSUE THREAD

**Issue by thomasdeng2027** [knmcguire/crazyflie_ros2_experimental#7]
Hello,

I know that this repo is not being worked on but I was trying to develop a mapping crazyflie drone swarm so I thought using webots with its realistic environemnts would make the most sense. While running ros2 launch crazyflie_ros2_simple_mapper simple_mapper_simulation_launch.py, I am able to connect to the robot and control it with teleop twist keyboard command but other than that, the drone stands still without ever running the simple_mapper script. Also, it appears that the cameras are not able to turn on which I am not sure is related. This can be seen in the picture attached.

Thanks for the help and the great work you have done and if possible, link relevant resources or any updates to my project that I may have not found yet.
![Screenshot from 2023-06-13 20-55-16](https://github.com/knmcguire/crazyflie_ros2_experimental/assets/76802324/ddbd240a-f38d-4f81-aed7-9111c5ae4c1f)

**Comment by TagirMuslimov** [comment]
Hello @TomoCoder123 

I have exactly the same problem with simple_mapper. Could you please advise how you solved this problem?

**Comment by knmcguire** [comment]
Hi! this repo is not really maintained anymore and has partly ported to crazyswarm2. So please take a look there: https://imrclab.github.io/crazyswarm2/tutorials.html#mapping-with-simple-mapper. It doesn't have webots intergrated though.

If you really want this particular repo to work then you have to make sure that you are using the same versions of the simulation and ROS2 or either be prepared to debug the issues by yourself.
