### ISSUE TITLE
Unable to run simple_mapper

### ISSUE THREAD

**Issue by cyborgdennett** [knmcguire/crazyflie_ros2_experimental#8]
At startup I get this error. I guess the package cannot find 

System:
WSL ubuntu 22.04
ROS Humble

command: ```ros2 launch crazyflie_ros2_simple_mapper simple_mapper_simulation_launch.py```

``` bash
[simple_mapper-4] Traceback (most recent call last):
[simple_mapper-4]   File "/home/casper/ros2/install/crazyflie_ros2_simple_mapper/lib/crazyflie_ros2_simple_mapper/simple_mapper", line 33, in <module>
[simple_mapper-4]     sys.exit(load_entry_point('crazyflie-ros2-simple-mapper==0.0.0', 'console_scripts', 'simple_mapper')())
[simple_mapper-4]   File "/home/casper/ros2/install/crazyflie_ros2_simple_mapper/lib/crazyflie_ros2_simple_mapper/simple_mapper", line 25, in importlib_load_entry_point
[simple_mapper-4]     return next(matches).load()
[simple_mapper-4]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[simple_mapper-4]     module = import_module(match.group('module'))
[simple_mapper-4]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[simple_mapper-4]     return _bootstrap._gcd_import(name[level:], package, level)
[simple_mapper-4]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[simple_mapper-4]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[simple_mapper-4]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[simple_mapper-4]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[simple_mapper-4]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[simple_mapper-4]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[simple_mapper-4]   File "/home/casper/ros2/install/crazyflie_ros2_simple_mapper/lib/python3.10/site-packages/crazyflie_ros2_simple_mapper/simple_mapper.py", line 20, in <module>
[simple_mapper-4]     from bresenham import bresenham
[simple_mapper-4] ModuleNotFoundError: No module named 'bresenham'
[ERROR] [simple_mapper-4]: process has died [pid 807747, exit code 1, cmd '/home/casper/ros2/install/crazyflie_ros2_simple_mapper/lib/crazyflie_ros2_simple_mapper/simple_mapper --ros-args'].
```

The error refers to these lines of code: in the launch file https://github.com/knmcguire/crazyflie_ros2_experimental/blob/f2b78f9a085e7421c0dfea02c383644819514410/crazyflie_ros2_simple_mapper/launch/simple_mapper_simulation_launch.py#L25-L29

**Comment by cyborgdennett** [comment]
On further reading, the bresenham library could not be found

https://github.com/knmcguire/crazyflie_ros2_experimental/blob/f2b78f9a085e7421c0dfea02c383644819514410/crazyflie_ros2_simple_mapper/crazyflie_ros2_simple_mapper/simple_mapper.py#L20

a simple ```pip install bresenham``` fixed the startup issue

**Comment by cyborgdennett** [comment]
Another issue I was having was with the cffirmware, it gives no error msg that it is not found or something like that. Was struggling to get that right for half hour (Ouch). but the fix is that you need to include ```/crazyflie-firmware/build```. In the readme it says only ```/crazyflie-firmware```.

**Comment by knmcguire** [comment]
Hi. Sorry for the reply. This repo is no longer maintainced. Lot of functionality has been moved to the crazyswarm2 project, where there is more support.

https://github.com/IMRCLab/crazyswarm2
